<a href="https://colab.research.google.com/github/Navyaaa2708/Python-Libraries/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
import numpy as np

In [ ]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

cols size should be same else it throws error

In [ ]:
a.ndim  #used to find dimensions of array

1

In [ ]:
b.ndim

2

In [ ]:
b.shape  #no of rows,cols

(2, 4)

In [ ]:
b.dtype  # for finding datatype of array

dtype('int64')

In [ ]:
b.itemsize  # returns the size, in bytes, of each element in the array

8

In [ ]:
b.nbytes  # 8*8 (no of elements * size of each element)

64

In [ ]:
c=np.array([[1,2,3,4,5,6,7,8],[7,8,9,0,34,56,56,27]])
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 7,  8,  9,  0, 34, 56, 56, 27]])

In [ ]:
c[1,2] # accesing elements of array using their index [row,col]

np.int64(9)

In [ ]:
c[1,:] # total row

array([ 7,  8,  9,  0, 34, 56, 56, 27])

In [ ]:
c[:,2] # separate column

array([3, 9])

In [ ]:
d= np.array([[[1,2],[3,4],[5,6]]])
d

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
d.ndim

3

In [ ]:
d.shape

(1, 3, 2)